from __future__ import annotations

from typing import Protocol

from backend.engine.models import Decision
from backend.engine.visibility import PlayerView


class Agent(Protocol):
    """AIWolf-inspired lifecycle used by the local game engine."""

    player_id: str

    def initialize(self, view: PlayerView, game_setting: dict) -> None: ...

    def update(self, view: PlayerView, request: str) -> None: ...

    def day_start(self) -> None: ...

    def talk(self) -> Decision: ...

    def vote(self) -> Decision: ...

    def attack(self) -> Decision: ...

    def divine(self) -> Decision: ...

    def guard(self) -> Decision: ...

    def witch_act(self, victim_id: str | None) -> list[Decision]: ...

    def shoot(self) -> Decision: ...

    def boom(self) -> Decision: ...

    def finish(self, winner: str | None) -> None: ...
